### ISSUE TITLE
XFSv5 UUID change

### ISSUE THREAD

**Issue by marcosfrm** [fdupoux/fsarchiver#4]
XFSv5 filesystems have their UUID stamped on every metadata block and cannot have it changed by xfs_admin until xfsprogs 4.2.0 and kernel 4.3 (when sb_meta_uuid was added). Once configured, it will set an incompatible superblock flag to prevent older kernels from mounting the fs.

http://oss.sgi.com/cgi-bin/gitweb.cgi?p=xfs/cmds/xfsprogs.git;a=commit;h=609f6bb20b7972c1a68370faea1dcbcf39912e07

http://oss.sgi.com/cgi-bin/gitweb.cgi?p=xfs/cmds/xfsprogs.git;a=commit;h=9c4e12fb60c15dc9c5e54041c9679454b42cb23e
http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=ce748eaa65f2e9392ba82726503c8d994ffd6393

If mkfs.xfs had an option to define UUID at filesystem creation it would solve the problem. With the advantage of keeping both UUIDs, internal and "visible", in sync (no incompat flag) and, thus, preserving compatibility with older kernels, 3.15+ (`-m crc=1,finobt=0`) or 3.16+ (`-m crc=1,finobt=1`). Such an option does exist (`-m uuid=<UUID>`). Unfortunately it was only added in mkfs.xfs 4.3.0.

http://oss.sgi.com/cgi-bin/gitweb.cgi?p=xfs/cmds/xfsprogs.git;a=commit;h=6af48b97f8ef7196e1303996995b3614dde24ec2

Is an option for FSArchiver require mkfs.xfs >= 4.3.0 when restoring XFSv5 fs?

**Comment by marcosfrm** [comment]
Actually `xfs_admin -U` does not return error on V5 filesystems since upstream disallowed that (xfsprogs 3.2.3). It always returns 0, despite doing nothing. FSArchiver succeeds, but user gets a random UUID after restfs.

**Comment by marcosfrm** [comment]
This behaviour until 4.2.0.

**Comment by fdupoux** [comment]
When the mkfs.xfs version is >= 4.3.0 and this is an XFSv4 should we use "-m uuid=<UUID>" or xfs_admin to set the UUID ?

**Comment by marcosfrm** [comment]
Both will work for XFSv4.

**Comment by fdupoux** [comment]
I have created a new branch for this issue: xfs-uuid

I have committed a change with solves the simple scenarios:
1) If we have mkfs.xfs >= 4.3.0 then we always use it to set the UUID rather than xfs_admin
2) If we have mkfs.xfs < 4.3.0 and an XFSv4 when we use xfs_admin to set the UUID

Next have to think about the complicated case of an XFSv5 with mkfs.xfs < 4.3.0 (with or without the sb_meta_uuid feature)

**Comment by fdupoux** [comment]
Is there a way to convert an XFSv4 to XFSv5 without rebuilding it ? I cannot find such an option in xfs_admin but I find it hard to believe the XFS developers have created a new format with no forward compatibility, considering there are a lot of RHEL users with XFSv4 that would need to migrate to XFSv5 in the longer term. They provided support from ext2 to ext3 to ext4 to btrfs so there must be the same thing for XFS versions ...

Also what's the situation with XFSv4 vs XFSv5 in RHEL/CentOS 7 ?

**Comment by marcosfrm** [comment]
No, there is no forward compatibility. It is not possible convert an existing XFSv4 fs to V5. Dave Chinner, current XFS maintainer, made it clear in 2012:

https://youtu.be/FegjLbCnoBw?t=36m3s

XFSv4 is the default filesystem in RHEL/CentOS 7 (V5 is not available at install time). But, since Red Hat already backported main V5 features to RHEL's 3.10 kernel (crc, finobt), I assume they will eventually switch to it in the future.

https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.0_Release_Notes/chap-Red_Hat_Enterprise_Linux-7.0_Release_Notes-File_Systems.html

Maybe some tool emerges to convert between the formats, but I would not hold my breath for it...

**Comment by marcosfrm** [comment]
I have tested xfs-uuid branch and it is working well with xfsprogs 4.3.0 (UUID set at mkfs time for both V4 and V5). With xfsprogs < 4.3.0, XFSv4 works (falling back to xfs_admin) and XFSv5 gets random UUID.

**Comment by fdupoux** [comment]
Thanks for your tests. I have merged this branch into master. Will create another UUID related branch for the remaining scenarios: XFSv5 with mkfs.xfs < 4.3.0.

I was tempted to restore the XFSv5 as XFSv4 in this case order to preserve the UUID which is important as the UUID is often used to identify the root filesystem during the boot process. I thought  users who really want an XFSv5 could just run an xfs_admin command to upgrade to XFSv5 manually, but it is not possible. It may still be the best thing to do as there is no perfect solution.

Refusing to restore is a possibility. But there are users who will be in an emergency to restore the filesystem (could be to restore a server for a disaster recovery). If all they have at that time is an old xfsprogs and they cannot restore their filesystems it can be very bad.

Restoring with the wrong UUID may be fine in most cases, but could be a big issue if this is a boot/root filesystem and grub or fstab uses the UUID to identify it.

Restoring an XFSv4 is not ideal as users may prefer XFSv5 to get the new features. But this way the users could restore their filesystem and it will still have the right UUID and the system will be able to start. And the compatibility will be even better so even older kernels will be able to mount it. So would be tempted to force an XFSv4 and print a warning saying the users needs to rerun the restore with an up to date xfsprogs if they really want XFSv5. This option is safer because if the situation is really urgent it will work. Having an XFSv4 instead of a XFSv5 should not be a massive problem.

**Comment by marcosfrm** [comment]
Yeah, I agree. Restore as V4 and print a warning.

**Comment by fdupoux** [comment]
Ok I have implemented this change in the new branch.

**Comment by marcosfrm** [comment]
xfs-uuid-v2 branch, restoring XFSv4 with xfsprogs 3.2.2:

```
Detected fileformat=2 in archive /mnt/v4.fsa
End of volume [/mnt/v4.fsa]
Current fsarchiver version: 0.6.20.0
Minimum fsarchiver version for that archive: 0.6.4.0
============= extracting filesystem 0 =============
Current fsarchiver version: 0.6.20.0
Minimum fsarchiver version for that filesystem: 0.6.20.0
strdico_get_string(dicocmdline, 'mkfsopt') doesn't exist
filesystem=[xfs]
filesystemoptions=[]
fsbytestotal=[7.99 GB]
fsbytesused=[168.00 KB]
getpathtoprog(mkfs.xfs)=[/usr/sbin/mkfs.xfs]
executing [mkfs.xfs -V]...
command [mkfs.xfs -V] returned 0
Detected mkfs.xfs version 3.2.2
getpathtoprog(mkfs.xfs)=[/usr/sbin/mkfs.xfs]
executing [mkfs.xfs -f /dev/sdc1    -b size=4096  -m crc=0  -m finobt=0  -n ftype=0 ]...
command [mkfs.xfs -f /dev/sdc1    -b size=4096  -m crc=0  -m finobt=0  -n ftype=0 ] returned 0
getpathtoprog(xfs_admin)=[/usr/sbin/xfs_admin]
executing [xfs_admin  -U   /dev/sdc1]...
command [xfs_admin  -U   /dev/sdc1] returned 2
fs_xfs.c#214,xfs_mkfs(): command [xfs_admin  -U   /dev/sdc1] failed
oper_restore.c#1281,extractar_filesystem_extract(): cannot format the filesystem xfs on partition /dev/sdc1
oper_restore.c#1525,oper_restore(): extract_filesystem(0) failed
```

**Comment by fdupoux** [comment]
Thanks for these tests. I have just pushed the fix for this bug and also for the error in the comments.

**Comment by marcosfrm** [comment]
Fix the "opearting" typo in the warning message and we are ready to go.

Ah, using mkfs=xfs with an image from other fs will assume XFSv4, as it does not have the XFS version stored right?

**Comment by fdupoux** [comment]
Yes that's right. As many functions in fsarchiver dico_get_u64() returns 0 when successful (when the item was found in the dictionary) and -1 when failed (it item not found). Hence the first line will apply: it will be set to XFS_SB_VERSION_4. Which is probably a safe choice as XFSv4 has better compatibility.

```
    if ((dico_get_u64(d, 0, FSYSHEADKEY_FSXFSVERSION, &temp64)!=0) || (temp64==XFS_SB_VERSION_4))
        xfsver = XFS_SB_VERSION_4;
    else
        xfsver = XFS_SB_VERSION_5;
```

So am going to close this issue if you are happy with it. Do you have other XFS fixes in mind or is that ok to release fsarchiver-0.6.20 ?

**Comment by marcosfrm** [comment]
Done. You can close it now.
