### ISSUE TITLE
pipable ?

### ISSUE THREAD

**Issue by eoli3n** [fdupoux/fsarchiver#40]
I want to use fsarchiver in my OS deploy project with bt sequential transfert to not store temp file on the destination.
Is there any way to add a ``pipable`` option ? as wimlib does 
https://wimlib.net/apidoc/group__G__writing__and__overwriting__wims.html#ga5e1c08e0079e90a1a7212815c749892e

**Comment by fdupoux** [comment]
fsarchiver will never be pipable as it needs to seek in files

**Comment by indianfoodyummy** [comment]
fdupoux... 
I had this same question, because this is the one feature that I think prevents this from being a perfect program...
And, I noticed in Mar 2019, dyejon submitted a pull request to address this opportunity, but you did not accept it?
Are you disinclined to accept dyejon's code because:
1) There are code flaws/limitations that need to be addressed in dyejon's proposed code (Which I could then work on), or
2) You are passionately disinclined to allow this functionality, even if it could be supported?
I ask, because although I can easily manually integrate dyejon's code into current master, presumably it could be done with automation by your accepting the pull request.  Before I spend time, I was hoping to better understand your interests.
Lastly... thank you for this program... it seems a significant improvement over ext4 dump/restore 
Best Regards.
