### ISSUE TITLE
RFE: Recover error correction features

### ISSUE THREAD

**Issue by lhernanz** [fdupoux/fsarchiver#43]
Hi,

according to http://forums.fsarchiver.org/viewtopic.php?f=14&t=1169, some forward error correction features were implemented to protect against archive corruption. Unfortunately, the code does not seem to be present in the last version.

Can you get the functionality back?

Thanks
Regards

**Comment by fdupoux** [comment]
Branch 0.7.x was a development branch just like linux-2.5 and the work and stabilization has never been completed because of lack of time. These features have never been released in a stable version so they cannot be put back. More work would be required in order to finish the development and make a new major stable release with these features.
