### ISSUE TITLE
Option to disable compression.

### ISSUE THREAD

**Issue by pthfdr-42** [fdupoux/fsarchiver#69]
Do not force the compression of archived files, as some people often manually compress them afterhand using standalone utilities like `lrzip` or `zpaq`. If you compress them beforehand it interferes with those better compression utilities.

**Comment by madbrain76** [comment]
I would like to see this option at all. When backing up to over a network to a file system that has compression, namely onto a name with ZFS and compression enabled, having a second level of compression only wastes time.

For example, on my Raspberry Pi 4, a tar backup onto my beefy NAS with ZFS takes about 8 minutes. But a backup using fsarchiver takes 14 minutes. This is because the bottleneck appears to be the Pi's CPU rather than the SD card or network.
